---
- name: check vm tools
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Get VM facts
      community.vmware.vmware_guest_facts:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ item.name }}"
      loop: "{{ vm_list }}"
      register: vm_facts
    - name: Check VMware Tools status
      debug:
        msg: "{{ item.guest.tools_status }}"
      loop: "{{ vm_facts.results }}"

