---
- name: Tạo VM trên ESXi

  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    esxi_hostname: "192.168.0.118"             # Địa chỉ của ESXi host
    esxi_username: "root"                    # Tài khoản ESXi
    esxi_password: "Gtelbca@123"                # Mật khẩu ESXi
    datastore_name: "datastore1"             # Datastore để lưu trữ VM
    folder_vm: "vm"
    vm_name: "MyNewVM1"                       # Tên VM mới
    vm_network: "VM Network"                 # Mạng cho VM
    vm_cpu: 2                                # Số lượng CPU
    vm_memory: 4096                          # Dung lượng RAM (MB)
    vm_disk_size: 20                         # Kích thước đĩa cứng (GB)
    iso_path: "[datastore1] modified_centos.iso" # Đường dẫn đến ISO trong datastore

  tasks:
    - name: create_VM
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ vm_name }}"
        state: poweredoff
        folder: "{{ folder_vm }}"
        guest_id: "otherGuest64"              # ID hệ điều hành, có thể tùy chọn
        disk:
          - size_gb: "{{ vm_disk_size }}"
            type: thin
            datastore: "{{ datastore_name }}"
        hardware:
          memory_mb: "{{ vm_memory }}"
          num_cpus: "{{ vm_cpu }}"
        networks:
          - name: "{{ vm_network }}"
        cdrom:
          -  type: "iso"
             iso_path: "{{ iso_path }}"
             controller_number: 0
             controller_type: ide
             unit_number: 0
#             type: cdrom
      delegate_to: localhost

    - name: Khởi động máy ảo để cài đặt từ ISO
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ vm_name }}"
        state: powered-on
      delegate_to: localhost

