---
- name: create_multi_vm
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: create_VM
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ item.name }}"
        state: powered-on
        folder: "{{ folder_vm }}"
        guest_id: "otherGuest64"              # ID hệ điều hành, có thể tùy chọn
        disk:
          - size_gb: "{{ vm_disk_size }}"
            type: thin
            datastore: "{{ datastore_name }}"
        hardware:
          memory_mb: "{{ vm_memory }}"
          num_cpus: "{{ vm_cpu }}"
        networks:
          - name: "{{ vm_network }}"
        cdrom:
          -  type: "iso"
             iso_path: "{{ iso_path }}"
             controller_number: 0
             controller_type: ide
             unit_number: 0
#             type: cdrom
      loop: "{{ vm_list }}"
      delegate_to: localhost

#    - name: Khởi động máy ảo để cài đặt từ ISO
#      community.vmware.vmware_guest_powerstate:
#        hostname: "{{ esxi_hostname }}"
#        username: "{{ esxi_username }}"
#        password: "{{ esxi_password }}"
#        validate_certs: no
#        name: "{{ item.name }}"
#        state: powered-on
#      delegate_to: localhost

