---
- name: Deploy and configure HAProxy
  hosts: all
  become: yes
  vars_files:
    - var_haproxy.yml
  tasks:

    - name: Install HAProxy
      ansible.builtin.yum:
        name: haproxy
        state: present

    - name: Deploy HAProxy configuration
      ansible.builtin.template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'

    - name: Restart HAProxy to apply changes
      ansible.builtin.systemd:
        name: haproxy
        enabled: true
        state: restarted

