---
- hosts: localhost
  name: Deploy the VCSA to an ESXi Host
  gather_facts: false
  vars:
    esxi_address: '10.2.220.26'
    esxi_username: 'root'
    esxi_password: 'To4@180922'
    vcenter_password: 'Admin@123'
    vcenter_hostname: 'vcenter-ansible.lab'
    vcenter_address: '10.2.220.110'
    net_prefix: '24'
    net_gateway: '10.2.220.253'
    dns_servers: '10.2.220.15'
    domain: 'local'
    vcsa_size: 'tiny'
    vcsa_ova_file: '/root/VMware-vCenter-Server-Appliance-8.0.1.00200-21860503_OVF10.ova'

  tasks:
  - name: Deploy vCenter
    vmware_deploy_ovf:
      hostname: '{{ esxi_address }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      name: '{{ vcenter_hostname }}'
      ovf: '{{ vcsa_ova_file }}'
      wait_for_ip_address: true
      validate_certs: no
      inject_ovf_env: true
      datastore: 'DS-LOCAL-10.2.220.26'
      networks: "{u'Network 1':u'DMZ-VLAN220-10.2.220.0'}"
      properties:
        DeploymentOption.value: '{{ vcsa_size }}'
        guestinfo.cis.appliance.net.addr.family: 'ipv4'
        guestinfo.cis.appliance.net.mode: 'static'
        guestinfo.cis.appliance.net.addr: '{{ vcenter_address }}'
        guestinfo.cis.appliance.net.pnid: "{{ vcenter_hostname }}.{{ domain }}"
        guestinfo.cis.appliance.net.prefix: '{{ net_prefix }}'
        guestinfo.cis.appliance.net.gateway: '{{ net_gateway }}'
        guestinfo.cis.appliance.net.dns.servers: '{{ dns_servers }}'
        guestinfo.cis.appliance.root.passwd: '{{ vcenter_password }}'
        guestinfo.cis.ceip_enabled: "False"
        guestinfo.cis.deployment.autoconfig: 'True'
        guestinfo.cis.vmdir.password: '{{ vcenter_password }}'
        domain: '{{ domain }}'
    delegate_to: localhost

#  - name: Wait for vCenter
#    community.vmware.vmware_about_facts:
#      hostname: '{{ vcenter_address }}'
#      username: 'administrator@vsphere.local'
#      password: '{{ vcenter_password }}'
#      validate_certs: no
#    delegate_to: localhost
#    retries: 20
#    delay: 60
#    register: result
#    until: result is succeeded

