---
- name: Get datastore information from ESXi host
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
    - var_host.yml
  tasks:
    - name: Gather datastore information
      community.vmware.vmware_datastore_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
#        esxi_hostname: "{{ item.ip }}"
      register: datastore_info
#      loop: "{{ host_esxi }}"
    
    - name: Display datastore information
      debug:
        var: datastore_info.datastores 
    - name: Find the datastore with the lowest usage
      set_fact:
        selected_datastore: "{{ datastore_info.datastores | sort(attribute='freeSpace') | first }}"
    - name: Display selected datastore information
      debug:
        msg: "The datastore with the lowest usage is {{ selected_datastore.name }} with {{ selected_datastore.freeSpace }} free space."
    - name: Clone VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        folder: "{{ folder_vm }}"
        state: poweredon
        resource_pool: "{{ resource_pool }}"
        name: "{{ item.name }}"
        template: "{{ vm_template }}" 
        hardware:
          memory_mb: "{{ item.memory_mb }}"
          num_cpus: "{{ item.num_cpus }}"
        networks:
          - name: "{{ item.network }}"
            ip: "{{ item.ip }}"
            netmask: "{{ item.netmask }}"  
            gateway: "{{ item.gateway }}" 
        wait_for_ip_address: yes
      loop: "{{ vm_list }}" 
      loop_control:
        label: "{{ item.name }}"

