---
- name: Tạo máy ảo trên vCenter
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
    vcenter_hostname: "192.168.0.115"
    vcenter_user: "administrator@vsphere.local"
    vcenter_password: "Gtelbca@123"
    datacenter_name: "Datacenter"
    cluster_name: "New Cluster"  
    datastore_name: "local"
    vm_name: "NewVM1"
    folder_name: "Datacenter/vm"
#    vm_template: "VM_Template"
    vm_network: "VM Network"
    vm_cpu: 2
    vm_memory: 4096
    vm_disk_size: 20
    guest_id: "rhel7_64Guest"

  tasks:
    - name: Connect to vCenter
      vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: no  # Không kiểm tra chứng chỉ (dùng cho chứng chỉ tự ký)
    
    - name: Create Virtual Machine from Template
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        cluster: "{{ cluster_name }}"
        datastore: "{{ datastore_name }}"
        folder: "{{ folder_name }}"
        name: "{{ vm_name }}"
#        template: "{{ vm_template }}"
        guest_id: "{{ guest_id }}"
        networks:
          - name: "{{ vm_network }}"
        disk:
          - size_gb: "{{ vm_disk_size }}"
        hardware:
          memory_mb: "{{ vm_memory }}"
          num_cpus: "{{ vm_cpu }}"
      delegate_to: localhost

