---
- name: Configure static IPs for multiple VMs on ESXi
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Set static IP for each VM
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        name: "{{ item.name }}"
        networks:
          - name: "{{ item.network_adapter }}"
            ip: "{{ item.ip }}"
            netmask: "{{ item.netmask }}"
            gateway: "{{ item.gateway }}"
        state: poweredon
      loop: "{{ vm_list }}"
      loop_control:
        label: "{{ item.name }}"

